Traceback (most recent call last):
  File "C:\Users\kmthayer\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Provide instructions for what your discord bot should do once it has logged in
@client.event
async def on_ready():
    # Load the discord channel you want to post to
    # TODO: put the discord channel id number below
    channel_id = 123456789
    channel = client.get_channel(channel_id)

    # Post a messages to your discord channel
    # TODO: modify this code to post at least 7 times
    await channel.send("Example post!")

    # Tell your bot to stop running
    await client.close()
    
# Now that we've defined how the bot should work, start running your bot
client.run(discord_token)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 17>[1;34m()[0m
[0;32m     14[0m     [38;5;28;01mawait[39;00m client[38;5;241m.[39mclose()
[0;32m     16[0m [38;5;66;03m# Now that we've defined how the bot should work, start running your bot[39;00m
[1;32m---> 17[0m [43mclient[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mdiscord_token[49m[43m)[49m

File [1;32m~\AppData\Local\Temp\ipykernel_41032\2345596534.py:30[0m, in [0;36mFakeDiscordClient.run[1;34m(self, token)[0m
[0;32m     28[0m print_info([38;5;124m"[39m[38;5;124mFake discord bot is fake logging in and starting to run[39m[38;5;124m"[39m)
[0;32m     29[0m [38;5;66;03m#test = await self._event.on_ready()[39;00m
[1;32m---> 30[0m [43masyncio[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_event[49m[38;5;241;43m.[39;49m[43mon_ready[49m[43m([49m[43m)[49m[43m)[49m

File [1;32mC:\Python310\lib\site-packages\nest_asyncio.py:35[0m, in [0;36m_patch_asyncio.<locals>.run[1;34m(main, debug)[0m
[0;32m     33[0m task [38;5;241m=[39m asyncio[38;5;241m.[39mensure_future(main)
[0;32m     34[0m [38;5;28;01mtry[39;00m:
[1;32m---> 35[0m     [38;5;28;01mreturn[39;00m [43mloop[49m[38;5;241;43m.[39;49m[43mrun_until_complete[49m[43m([49m[43mtask[49m[43m)[49m
[0;32m     36[0m [38;5;28;01mfinally[39;00m:
[0;32m     37[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m task[38;5;241m.[39mdone():

File [1;32mC:\Python310\lib\site-packages\nest_asyncio.py:89[0m, in [0;36m_patch_loop.<locals>.run_until_complete[1;34m(self, future)[0m
[0;32m     86[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m f[38;5;241m.[39mdone():
[0;32m     87[0m     [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m(
[0;32m     88[0m         [38;5;124m'[39m[38;5;124mEvent loop stopped before Future completed.[39m[38;5;124m'[39m)
[1;32m---> 89[0m [38;5;28;01mreturn[39;00m [43mf[49m[38;5;241;43m.[39;49m[43mresult[49m[43m([49m[43m)[49m

File [1;32mC:\Python310\lib\asyncio\futures.py:201[0m, in [0;36mFuture.result[1;34m(self)[0m
[0;32m    199[0m [38;5;28mself[39m[38;5;241m.[39m__log_traceback [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m    200[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m--> 201[0m     [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception
[0;32m    202[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_result

File [1;32mC:\Python310\lib\asyncio\tasks.py:232[0m, in [0;36mTask.__step[1;34m(***failed resolving arguments***)[0m
[0;32m    228[0m [38;5;28;01mtry[39;00m:
[0;32m    229[0m     [38;5;28;01mif[39;00m exc [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    230[0m         [38;5;66;03m# We use the `send` method directly, because coroutines[39;00m
[0;32m    231[0m         [38;5;66;03m# don't have `__iter__` and `__next__` methods.[39;00m
[1;32m--> 232[0m         result [38;5;241m=[39m [43mcoro[49m[38;5;241;43m.[39;49m[43msend[49m[43m([49m[38;5;28;43;01mNone[39;49;00m[43m)[49m
[0;32m    233[0m     [38;5;28;01melse[39;00m:
[0;32m    234[0m         result [38;5;241m=[39m coro[38;5;241m.[39mthrow(exc)

Input [1;32mIn [4][0m, in [0;36mon_ready[1;34m()[0m
[0;32m      7[0m channel [38;5;241m=[39m client[38;5;241m.[39mget_channel(channel_id)
[0;32m      9[0m [38;5;66;03m# Post a messages to your discord channel[39;00m
[0;32m     10[0m [38;5;66;03m# TODO: modify this code to post at least 7 times[39;00m
[1;32m---> 11[0m [38;5;28;01mawait[39;00m channel[38;5;241m.[39msend([38;5;124m"[39m[38;5;124mExample post![39m[38;5;124m"[39m)
[0;32m     13[0m [38;5;66;03m# Tell your bot to stop running[39;00m
[0;32m     14[0m [38;5;28;01mawait[39;00m client[38;5;241m.[39mclose()

[1;31mTypeError[0m: object NoneType can't be used in 'await' expression
TypeError: object NoneType can't be used in 'await' expression

