Traceback (most recent call last):
  File "C:\Users\kmthayer\AppData\Roaming\Python\Python310\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Set up your Discord connection
# TODO: put the discord token for your bot below
discord_token = "m#5@_fake_discord_token_$%Ds"
client = discord.Client(intents=discord.Intents.default())
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Input [1;32mIn [3][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m# Set up your Discord connection[39;00m
[0;32m      2[0m [38;5;66;03m# TODO: put the discord token for your bot below[39;00m
[0;32m      3[0m discord_token [38;5;241m=[39m [38;5;124m"[39m[38;5;124mm#5@_fake_discord_token_$[39m[38;5;124m%[39m[38;5;124mDs[39m[38;5;124m"[39m
[1;32m----> 4[0m client [38;5;241m=[39m discord[38;5;241m.[39mClient(intents[38;5;241m=[39m[43mdiscord[49m[38;5;241;43m.[39;49m[43mIntents[49m[38;5;241m.[39mdefault())

[1;31mAttributeError[0m: 'types.SimpleNamespace' object has no attribute 'Intents'
AttributeError: 'types.SimpleNamespace' object has no attribute 'Intents'

